import inspect
import json
import time
from typing import Callable, Dict
import redis.asyncio as redis

from core.commons.logger import logger
from global_config import MEMO_REDIS_URL, REDIS_POOL_SIZE, DEFAULT_EXPIRE_SECONDS
from core.commons.decorator import task_handler


class RedisService:
    """
    Redis is NOT the source of truth.

    1. Memo Redis:
        Key: "memo:{client_id}:{history_id}" or "longterm:{client_id}"
        - Hot cache for recent conversation messages
        - MySQL is the only truth source
        - Redis may NOT exist for a conversation

    2. Task Redis:
        Key: "task:{task_hash}"
        Task_hash: Generated by hash(cilent_id + history_id + tool_id) in Tool Service.
        Caution: the task id store in task info not be seen as redis key, but it is Unique key in mysql.
        The task_hash will be trashed after task finished, it doesnot persist in MySQL.
        - Runtime task lock & status only
        - Only stores pending / running
        - Absence means task is finished or not created
    """

    def __init__(
        self,
        memo_redis_url: str = MEMO_REDIS_URL,
    ):
        self._memo_redis = redis.from_url(
            memo_redis_url,
            decode_responses=True,
            max_connections=REDIS_POOL_SIZE,
            socket_keepalive=True,
        )


    async def _close(self) -> None:
        await self._memo_redis.aclose()

    # ------------------------------------------------------------------
    # Handler Export
    # ------------------------------------------------------------------

    def export_handlers(self) -> Dict[str, Callable]:
        handlers: Dict[str, Callable] = {}

        for attr_name in dir(self):
            if attr_name.startswith("_"):
                continue

            attr = getattr(self, attr_name)
            if not callable(attr):
                continue

            task_name = getattr(attr, "_handler_name", None)
            if not task_name:
                continue

            if not inspect.iscoroutinefunction(attr):
                raise TypeError(
                    f"[RedisService][export_handlers] Task handler '{task_name}' must be async function"
                )

            handlers[task_name] = attr

        return handlers

    # ------------------------------------------------------------------
    # Key Builders
    # ------------------------------------------------------------------

    def _build_memo_key(self, payload: dict) -> str:
        client_id = payload.get("client_id")
        history_id = payload.get("history_id")

        if not all([client_id, history_id]):
            raise KeyError("[RedisService][_build_memo_key] client_id / history_id required")

        return f"memo:{client_id}:{history_id}"

    def _build_longterm_key(self, payload: dict) -> str:
        client_id = payload.get("client_id")

        if not client_id:
            raise KeyError("[RedisService][_build_longterm_key] client_id required")

        return f"longterm:{client_id}"

    def _build_task_key(self, payload: dict) -> str:
        '''build task key'''
        task_hash = payload.get("task_hash")
        if not (task_hash):
            raise KeyError("[RedisService][_build_task_key] task_hash required")

        return f"task:{task_hash}"

    # ------------------------------------------------------------------
    # Memo Redis (Conversation Cache)
    # ------------------------------------------------------------------

    @task_handler("redis.memo.append_messages")
    async def append_messages(self, payload: dict) -> dict:
        """
        Append message ONLY IF redis key already exists.
        This method should only be called after append message to MySQL and then backfilling Redis.

        Args:
            payload: Dict, the format is {
                "client_id": "{{ cid }} : to indicate which user the data is from.",
                "history_id": "{{ hid }} : to indicate which dialog history the data belong to.",
                "session_id": "{{ sid }} : to indicate which tab the data belong to",
                "messages": {
                    "role": 'human', 'ai', 'system', 'tool', 'info'
                    "content": "message content",
                    "think": "",
                    "extra": {...},
                    "info": {
                        "model": "...",
                        "total_duration": "...",
                        "model_provider": "...",
                        "total_tokens": int,
                        "id": "",
                    }, 
                    "node_id": int,
                    "parent_id": int,
                    "msg_cursor": int,
                    "timestamp": int,
                    "created_at": str
                }
            }

        Return:
            dict, the format is {
                "success": True / False,
                "messages": "success / fail: {e}",
            }
        """
        logger.info(f"[RedisService][append_messages] enter.")
        try:
            key = self._build_memo_key(payload)

            # Redis miss → skip silently
            if not await self._memo_redis.exists(key):
                logger.warning(
                    f"[RedisService][append_messages] Redis key not exists."
                )
                return {
                    "success": True,
                    "messages": "success",
                }

            messages = payload.get("messages", {})

            async with self._memo_redis.pipeline() as pipe:
                pipe.rpush(key, json.dumps(messages, ensure_ascii=False))

                pipe.expire(key, DEFAULT_EXPIRE_SECONDS)
                await pipe.execute()

            return {
                "success": True,
                "messages": "success",
            }

        except Exception as e:
            logger.exception(f"[RedisService][append_messages] error: {e}")
            return {
                "success": False, 
                "messages": f"fail: {e}"
            }
        
    @task_handler("redis.memo.backfill_messages")
    async def backfill_messages(self, payload: dict) -> dict:
        """
        Backfill FULL messages into Redis (overwrite mode).

        This method should only be called after fetching FULL messages from MySQL.

        Args:
            payload: Dict, the format is {
                "client_id": "{{ cid }}",
                "history_id": "{{ hid }}",
                "session_id": "{{ sid }}",
                "messages": [ ... ]  # FULL message list
            }

        Return:
            dict, the format is {
                "success": True / False,
                "messages": "success / fail: {e}",
            }
        """
        logger.info(f"[RedisService][backfill_messages] enter.")

        try:
            key = self._build_memo_key(payload)
            messages = payload.get("messages", [])

            if not isinstance(messages, list):
                raise ValueError("[RedisService][backfill_messages] messages must be a list")

            # Empty list is allowed → clear cache
            async with self._memo_redis.pipeline() as pipe:
                # ---- Overwrite instead of append ----
                pipe.delete(key)

                if messages:
                    pipe.rpush(
                        key,
                        *[json.dumps(msg, ensure_ascii=False) for msg in messages]
                    )

                pipe.expire(key, DEFAULT_EXPIRE_SECONDS)
                await pipe.execute()

            return {
                "success": True,
                "messages": "success",
            }

        except Exception as e:
            logger.exception(f"[RedisService][backfill_messages] error: {e}")
            return {
                "success": False,
                "messages": f"fail: {e}"
            }
        
    @task_handler("redis.memo.get_recent_messages")
    async def get_recent_messages(self, payload: dict) -> dict:
        """
        Fetch FULL messages from Redis cache (no cursor).

        Redis miss should be handled by caller (fallback to MySQL and backfill).

        Args:
            payload: Dict, the format is {
                "client_id": "{{ cid }}",
                "history_id": "{{ hid }}",
                "session_id": "{{ sid }}"
            }

        Return:
            dict, the format is {
                "success": True / False,
                "messages": "fail: {e}" or [...] (list of message dicts),
                "cache_hit": bool
            }
        """
        logger.info("[RedisService][get_recent_messages] enter.")

        try:
            key = self._build_memo_key(payload)

            # ---- Fetch FULL list from Redis ----
            raw = await self._memo_redis.lrange(key, 0, -1)
            if not raw:
                # Redis miss: empty or expired
                return {
                    "success": True,
                    "messages": [],
                    "cache_hit": False,
                }

            # ---- Decode all messages ----
            messages = [json.loads(m) for m in raw]

            return {
                "success": True,
                "messages": messages,
                "cache_hit": True,
            }

        except Exception as e:
            logger.exception(f"[RedisService][get_recent_messages] error: {e}")
            return {
                "success": False,
                "messages": f"fail: {e}",
            }

    # ------------------------------------------------------------------
    # TTL
    # ------------------------------------------------------------------

    @task_handler("redis.common.set_expire")
    async def set_expire(self, payload: dict, ttl_seconds: int = DEFAULT_EXPIRE_SECONDS) -> dict:
        """
        set_expire to given ttl_seconds.
        In order to unified:
        - When payload dictionary contains key 'task_hash', it will be seen as set tasks TTL in redis.
        - Else set conversation message list's TTL.
        """
        logger.info(f"[RedisService][set_expire] enter.")
        try:
            await self._memo_redis.expire(
                self._build_memo_key(payload), ttl_seconds
            )
        except Exception as e:
            logger.exception(f"[RedisService][set_expire] error: {e}")
            return {"success": False, "messages": f"fail: {e}"}
        return {
                "success": True,
                "messages": "success",
            }

    @task_handler("redis.common.expire_immediately")
    async def expire_immediately(self, payload: dict) -> dict:
        """
        Expire key immediately.

        Unified behavior:
        - When payload contains 'task_hash', fetch task info then delete task redis key.
        - Else delete memo redis key.
        """
        logger.info(f"[RedisService][expire_immediately] enter.")
        try:
            await self._memo_redis.delete(
                self._build_memo_key(payload)
            )

            return {
                "success": True,
                "messages": "success",
            }

        except Exception as e:
            logger.exception(f"[RedisService][expire_immediately] error: {e}")
            return {
                "success": False,
                "messages": f"fail: {e}",
            }


redis_server = RedisService(MEMO_REDIS_URL)
