# Global configuration settings for the Apix Agent Core module.

import os
import uuid
import platform

OPERATION_SYSTEM = platform.system().lower()

DEBUG = False
TRACE = True
CHECK_SERVER_HEALTH = False  # Enable or disable services health checks

OUTPUT_GRAPH_PNG = False  # Whether to output the agent graph as a PNG file

BASE_DIR = "../model_running_time/" # Download cache dir

SANDBOX_DOCKER_IMAGE_NAME = "agent-sandbox:latest" # Sandbox image name.

BASE_URL = {       # Base URL for the LLM service
    # Ollama
    'ollama:local': 'http://localhost:11434',  # Local
    'ollama': 'https://ollama.com',  # Cloud
    
    # OpenAI
    'openai': 'https://api.openai.com',
    
    # Google (Gemini)
    'google': 'https://generativelanguage.googleapis.com',
    
    # Qwen (通义千问)
    'qwen': 'https://dashscope.aliyuncs.com',
    
    # Qianfan (百度千帆)
    'qianfan': 'https://qianfan.baidubce.com',
    
    # DeepSeek
    'deepseek': 'https://api.deepseek.com',

    # Moonshot (月之暗面)
    'moonshot': 'https://api.moonshot.cn',
}  

MAX_LLM_CONNECTIONS = 12  # Maximum number of llm connections

# KEEP_ALIVE_S = 300  # Keep-alive time for connections in seconds

APIX_SERVICE_URL = "http://localhost:5090"  # Apix service URL

AGENT_SERVICE_URL = "http://localhost:5091"  # Apix service URL

TOOLS_SERVICE_URL = "http://localhost:5092"  # Tools service URL

MEMORY_SERVICE_URL = "ws://localhost:5093"  # Memory service URL, websocket url

MEMORY_SERVICE_BASE_URL = "http://localhost:5093"

FILE_SERVICE_URL = "http://localhost:5094"

PUBLIC_FILE_ADRESS = "" # Files generated by agent will upload at this internet adress

AGENT_SERVICE_ID = str(uuid.uuid4().hex)

LOAD_FORIGN_TOOL = False

GRAPH_CACHE_TTL = 100 * 60          # seconds
GRAPH_CACHE_CLEAN_INTERVAL = 60   # seconds

_ORIGINAL_PROXY_ENV = {
    "HTTP_PROXY": os.environ.get("HTTP_PROXY"),
    "HTTPS_PROXY": os.environ.get("HTTPS_PROXY"),
    "NO_PROXY": os.environ.get("NO_PROXY"),
}
