# Global configuration settings for the Apix Agent Core module.

import os
import uuid
import platform

OPERATION_SYSTEM = platform.system().lower()

DEBUG = True
TRACE = True
CHECK_SERVER_HEALTH = False  # Enable or disable services health checks

OUTPUT_GRAPH_PNG = False  # Whether to output the agent graph as a PNG file

BASE_DIR = "../model_running_time/" # Download cache dir

SANDBOX_DOCKER_IMAGE_NAME = "agent-sandbox:latest" # Sandbox image name.

TOOLS_MAX_OUTPUT_LENGTH = 32000

BASE_URL = {       # Base URL for the LLM service
    # Ollama
    'ollama:local': 'http://localhost:11434',  # Local
    'ollama': 'https://ollama.com',  # Cloud
    
    # OpenAI
    'openai': 'https://api.openai.com',
    
    # Google (Gemini)
    'google': 'https://generativelanguage.googleapis.com',
    
    # Qwen (通义千问)
    'qwen': 'https://dashscope.aliyuncs.com',
    
    # Qianfan (百度千帆)
    'qianfan': 'https://qianfan.baidubce.com',
    
    # DeepSeek
    'deepseek': 'https://api.deepseek.com',

    # Moonshot (月之暗面)
    'moonshot': 'https://api.moonshot.cn',

    # XiaomiMIMO
    'xiaomimimo': 'https://api.xiaomimimo.com',
}  


MAX_RETRY = 8 # Max retry when llm_call failure, make sure it great than 3

TASK_SERVER_BASE_URL = "http://localhost:5090"

AGENT_SERVICE_URL = "http://localhost:5091"  # Apix service URL

TOOLS_SERVICE_URL = "http://localhost:5092"  # Tools service URL

MEMORY_SERVICE_BASE_URL = "http://localhost:5093"

FILE_SERVICE_URL = "http://localhost:5094"

PUBLIC_FILE_ADRESS = "" # Files generated by agent will upload at this internet adress

AGENT_SERVICE_ID = str(uuid.uuid4().hex)

LOAD_FORIGN_TOOL = False

GENERATION_TTL = 600  # Clear those finished and aborted generation ctx, seconds
CONTIANER_TTL = 6000
GRAPH_CACHE_TTL = 600
CACHE_CLEAN_INTERVAL = 300

_ORIGINAL_PROXY_ENV = {
    "HTTP_PROXY": os.environ.get("HTTP_PROXY"),
    "HTTPS_PROXY": os.environ.get("HTTPS_PROXY"),
    "NO_PROXY": os.environ.get("NO_PROXY"),
}
